### ISSUE TITLE
host file error when running beaker

### ISSUE THREAD

**Issue by eljohn1014** [evenup/evenup-sssd#20]
Hello, I ran bundle install and then went to run bundle exec rake acceptance, I am getting the error "parse_hosts_file': Host file '/sssd/spec/acceptance/nodesets/default.yml' does not exist! (ArgumentError)"

**Comment by jlambert121** [comment]
It looks like I didn't put a default.yml in there, you can set a specific host with something like:  "BEAKER_set=centos-70-x64 bundle exec rspec spec/acceptance"

**Comment by eljohn1014** [comment]
in the acceptance folder there is only a class_spec.rb file, it is still looking for the nodesets/ yaml file, is this something I should be adding in myself?

**Comment by jlambert121** [comment]
That is odd, my machine has them.  Let me get those added - not sure why they aren't there.

**Comment by jlambert121** [comment]
There we go, now they're there, sorry about that.  Unfortunately they don't do much right now, I really need to have one box spin up an LDAP server and configure it so the client can test auth, just haven't had time to dive into that yet.
