### ISSUE TITLE
add a few more parameters

### ISSUE THREAD

**Issue by mattatnersc** [evenup/evenup-sssd#31]
Is it possible to add a few more parameters?  I'd be interested in changing debug_level and enumerate values in sssd.conf.  The default value for debug_level is way too verbose IMHO and sssd has an open bug for enumerate when LDAP directories are very large.

**Comment by jlambert121** [comment]
Certainly!  I believe preventing enumeration is in master (but might not have made it into a release yet).  If you want to send a PR I'll look at getting it merged.

**Comment by mattatnersc** [comment]
On Thu, Jun 11, 2015 at 11:34:29AM -0700, Justin Lambert wrote:
> Certainly!  I believe preventing enumeration is in master (but might not have made it into a release yet).  If you want to send a PR I'll look at getting it merged.

Make a pull request after I make a patch for changing debug_level,
right?  I see that there's already a patch for enumerate.

**Comment by jlambert121** [comment]
Yeah, if there's other parameters you want to adjust (such as debug_level) throw a PR over and I'll get it merged and I can tag a release as well.
